### ISSUE TITLE
Deploying a Specific Tag

### ISSUE THREAD

**Issue by MarkBorcherding** [newrelic/centurion#122]
I don't see where the `tag` is being passed down to deploy. I've started to [fix it here](https://github.com/asynchrony/centurion/tree/add-tag-to-service), but wanted to make sure it is really broken first. 

I have the following project

```ruby
namespace :environment do
  task :common do
    set :image, 'redis'
  end

  desc 'Staging environment'
  task staging: :common do
    set_current_environment(:staging)
    host_port 10_234, container_port: 9292
    host '127.0.0.1:4243'
    host '127.0.0.1:4244'
    set :container_hostname, ->(s) { s }
  end
end
```
I run the following command to deploy a specific tag.
```
$  centurion -e staging -a deploy -p example-app -t 2.6.17
```

I get the following output.

```
** Invoke deploy:determine_image_id_from_first_server (first_time)                                                                                                      [645/1859]
** Execute deploy:determine_image_id_from_first_server
** Invoke deploy:verify_image (first_time)
** Execute deploy:verify_image
** Invoke deploy:stop (first_time)
** Execute deploy:stop
** Invoke deploy:start_new (first_time)
** Execute deploy:start_new
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/docker_via_api.rb:77:in `create_container': #<Excon::Response:0x007fed048351f0
 @data={:body=>"No such image: redis (tag: latest)\n", :headers=>{"Content-Type"=>"text/plain; charset=utf-8", "Date"=>"Tue, 09 Jun 2015 00:57:06 GMT", "Content-Length"=>"35"}, :
status=>404, :status_line=>"HTTP/1.1 404 Not Found\r\n", :reason_phrase=>"Not Found", :remote_ip=>"127.0.0.1", :local_port=>60632, :local_address=>"127.0.0.1"}, @body="No such im
age: redis (tag: latest)\n", @headers={"Content-Type"=>"text/plain; charset=utf-8", "Date"=>"Tue, 09 Jun 2015 00:57:06 GMT", "Content-Length"=>"35"}, @status=404, @remote_ip="127
.0.0.1", @local_port=60632, @local_address="127.0.0.1"> (RuntimeError)
        from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/deploy.rb:104:in `start_new_container'
        from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/tasks/deploy.rake:100:in `block (3 levels) in <top (required)>'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/deploy_dsl.rb:8:in `call'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/deploy_dsl.rb:8:in `block (2 levels) in on_each_docker_host'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/docker_server_group.rb:22:in `call'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/docker_server_group.rb:22:in `block in each'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/docker_server_group.rb:20:in `each'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/docker_server_group.rb:20:in `each'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/deploy_dsl.rb:8:in `block in on_each_docker_host'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-1.7.4/lib/centurion/deploy_dsl.rb:8:in `tap'
        from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/centurion-
1.7.4/lib/centurion/deploy_dsl.rb:8:in `on_each_docker_host'
```

**Comment by relistan** [comment]
@MarkBorcherding my apology. I need to be more on top of these and I apologize that I didn't respond to this yesterday. We just found the same thing and I've put in PR #123 to fix it.

**Comment by relistan** [comment]
Closing as this is fixed on master.
