### ISSUE TITLE
How to deploy private image from Docker hub?

### ISSUE THREAD

**Issue by roonglit** [newrelic/centurion#88]
Hi, 

This may be similar to #76. I tried to set up credential on remote server but it didn't work. 

Here is my configuration for my public image

```yml
namespace :environment do
  task :common do
    set :image, 'roonglit/docker-test'
  end

  desc 'Staging environment'
  task :staging => :common do
    set_current_environment(:staging)
    host 'my-host-here'
  end
end
```

when I call rolling_deploy action, it's working fine. I want to deploy my private image, so I change the configuration to: 

```yml
namespace :environment do
  task :common do
    set :image, 'registry.hub.docker.com/hipflat/website'
    set :registry_user, 'my_username_here'
    set :registry_password, 'my_password_here'
  end

  desc 'Staging environment'
  task :staging => :common do
    set_current_environment(:staging)
    host 'my-host-here'
  end
end
```

when I call rolling_deploy action, I got an error. 

```
* Invoke environment:staging (first_time)
** Invoke environment:common (first_time)
** Execute environment:common
** Execute environment:staging
** Invoke rolling_deploy (first_time)
** Execute rolling_deploy
** Invoke deploy:get_image (first_time)
** Execute deploy:get_image
** Invoke deploy:pull_image (first_time)
** Execute deploy:pull_image
I, [2015-01-23T10:49:05.880898 #955]  INFO -- : Fetching image registry.hub.docker.com/hipflat/website:latest IN PARALLEL

I, [2015-01-23T10:49:05.881224 #955]  INFO -- : Using CLI to pull
I, [2015-01-23T10:49:05.883343 #955]  INFO -- : Using CLI to pull
Pulling repository registry.hub.docker.com/hipflat/website
Pulling repository registry.hub.docker.com/hipflat/website
2015/01/23 10:49:09 Error: image hipflat/website:latest not found
2015/01/23 10:49:09 Error: image hipflat/website:latest not found
/Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/logging.rb:62:in `validate_status': The command failed with a non-zero exit status: 1. Command: 'docker -H=tcp://hipflat-website.cloudapp.net:2375 pull registry.hub.docker.com/hipflat/website:latest' (RuntimeError)
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/logging.rb:48:in `run_without_echo'
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/logging.rb:25:in `echo'
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/docker_via_cli.rb:17:in `pull'
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/tasks/deploy.rake:187:in `block (3 levels) in <top (required)>'
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/docker_server_group.rb:28:in `call'
	from /Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/centurion-1.4.1/lib/centurion/docker_server_group.rb:28:in `block (2 levels) in each_in_parallel'
```

I tried using docker -H my-host-server:2375 pull hipflat/website, and it's working fine both my local pc, and my remote server (which I'm trying to deploy image with Centurion). 

Could you give me some suggestions on what I need to do next?

**Comment by roonglit** [comment]
Sorry guys. I found out how to solve this now. 

I need to call docker -H my-host-server:2375 login on my local pc first. After that, Centurion is working like a charm.
